Repository codesquad-members-2023/be-java-cafe-max, pull requests merged in 2023-04, with the labels that each got.

#43 [지구] Step-1,2 구현
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/HomeController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/dto/ArticleDTO.java
  src/main/java/kr/codesqaud/cafe/controller/dto/UserJoinDTO.java
  src/main/java/kr/codesqaud/cafe/controller/dto/UserReadDTO.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/css/index.css
  src/main/resources/static/css/post/form.css
  src/main/resources/static/css/post/show.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/css/styles.css
  src/main/resources/static/css/user/form.css
  src/main/resources/static/css/user/list.css
  src/main/resources/static/css/user/login.css
  src/main/resources/static/favicon.ico
  src/main/resources/static/fonts/glyphicons-halflings-regular.eot
  src/main/resources/static/fonts/glyphicons-halflings-regular.svg
  src/main/resources/static/fonts/glyphicons-halflings-regular.ttf
  src/main/resources/static/fonts/glyphicons-halflings-regular.woff
  src/main/resources/static/fonts/glyphicons-halflings-regular.woff2
  src/main/resources/static/images/80-text.png
  src/main/resources/static/index.html
  src/main/resources/static/js/bootstrap.min.js
  src/main/resources/static/js/jquery-2.2.0.min.js
  src/main/resources/static/js/scripts.js
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/list.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/nav.html
  src/main/resources/templates/post/form.html
  src/main/resources/templates/post/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/profile.html
Labels: enhancement

#19 [Hana] step-1 구현
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/HomeController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/user/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/user/User.java
  src/main/java/kr/codesqaud/cafe/user/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/list.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/nav.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
Labels: step-1

#40 [파이] 회원가입 기능, 회원 목록 조회 기능, 회원 프로필 조회 기능 , 글 쓰기 기능, 글 목록 조회 기능 구현
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/dto/PostingRequest.java
  src/main/java/kr/codesqaud/cafe/controller/dto/SignUpRequest.java
  src/main/java/kr/codesqaud/cafe/controller/dto/UserDto.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/layout/navbar.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
Labels: enhancement, step-1, step-2

#37 [이안] 스프링 카페1 구현
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/HomeController.java
  src/main/java/kr/codesqaud/cafe/board/controller/BoardController.java
  src/main/java/kr/codesqaud/cafe/board/domain/BoardPost.java
  src/main/java/kr/codesqaud/cafe/board/repository/BoardRepository.java
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/user/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/user/domain/User.java
  src/main/java/kr/codesqaud/cafe/user/dto/UserDto.java
  src/main/java/kr/codesqaud/cafe/user/repository/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/templates/board/detail.mustache
  src/main/resources/templates/board/write.mustache
  src/main/resources/templates/index.mustache
  src/main/resources/templates/layout/footer.mustache
  src/main/resources/templates/layout/header.mustache
  src/main/resources/templates/layout/navbarHeader.mustache
  src/main/resources/templates/user/form.mustache
  src/main/resources/templates/user/form_failed.mustache
  src/main/resources/templates/user/list.mustache
  src/main/resources/templates/user/profile.mustache
Labels: step-1, step-2

#36 [보노] step-1/step-2 구현
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleMemoryRepository.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserMemoryRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/layout/nav.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/form_update.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
Labels: step-1, step-2

#31 [ light ] 회원가입, 회원가입 목록 출력, 프로필조회, 회원수정 / 게시글 작성, 목록, 조회
  build.gradle
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/member/User.java
  src/main/java/kr/codesqaud/cafe/domain/member/UserMemoryImpl.java
  src/main/java/kr/codesqaud/cafe/domain/member/UserRepository.java
  src/main/java/kr/codesqaud/cafe/domain/question/Article.java
  src/main/java/kr/codesqaud/cafe/domain/question/ArticleMemoryImpl.java
  src/main/java/kr/codesqaud/cafe/domain/question/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/dto/ArticleFormDto.java
  src/main/java/kr/codesqaud/cafe/dto/SignUpFormDto.java
  src/main/java/kr/codesqaud/cafe/dto/UpdateFormDto.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/update_form.html
Labels: enhancement, step-1, step-2

#30 [Jinny] 스프링 카페 미션 - step1, 2 구현
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/DTO/ArticleDTO.java
  src/main/java/kr/codesqaud/cafe/DTO/UserDTO.java
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/MainController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/list.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/head.html
  src/main/resources/templates/layout/navbar.html
  src/main/resources/templates/layout/subnav.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile.html
Labels: step-1, step-2

#1 [Albert] Java-Cafe V1
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/account/User.java
  src/main/java/kr/codesqaud/cafe/account/UserController.java
  src/main/java/kr/codesqaud/cafe/account/UserService.java
  src/main/java/kr/codesqaud/cafe/account/UsersRepository.java
  src/main/java/kr/codesqaud/cafe/account/form/JoinForm.java
  src/main/java/kr/codesqaud/cafe/account/form/LoginForm.java
  src/main/java/kr/codesqaud/cafe/account/form/ProfileForm.java
  src/main/java/kr/codesqaud/cafe/account/form/ProfileSettingForm.java
  src/main/java/kr/codesqaud/cafe/account/form/UsersForm.java
  src/main/java/kr/codesqaud/cafe/post/MainController.java
  src/main/java/kr/codesqaud/cafe/post/Post.java
  src/main/java/kr/codesqaud/cafe/post/PostController.java
  src/main/java/kr/codesqaud/cafe/post/PostService.java
  src/main/java/kr/codesqaud/cafe/post/PostsRepository.java
  src/main/java/kr/codesqaud/cafe/post/form/PostForm.java
  src/main/java/kr/codesqaud/cafe/post/form/SimplePostForm.java
  src/main/resources/application.properties
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/css/styles.css
  src/main/resources/static/favicon.ico
  src/main/resources/static/fonts/glyphicons-halflings-regular.eot
  src/main/resources/static/fonts/glyphicons-halflings-regular.svg
  src/main/resources/static/fonts/glyphicons-halflings-regular.ttf
  src/main/resources/static/fonts/glyphicons-halflings-regular.woff
  src/main/resources/static/fonts/glyphicons-halflings-regular.woff2
  src/main/resources/static/images/80-text.png
  src/main/resources/static/index.html
  src/main/resources/static/js/bootstrap.min.js
  src/main/resources/static/js/jquery-2.2.0.min.js
  src/main/resources/static/js/scripts.js
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/list.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/account/join.html
  src/main/resources/templates/account/login.html
  src/main/resources/templates/account/members.html
  src/main/resources/templates/account/profile.html
  src/main/resources/templates/account/profileUpdate.html
  src/main/resources/templates/error/3xx.html
  src/main/resources/templates/error/4xx.html
  src/main/resources/templates/error/5xx.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/index.html
  src/main/resources/templates/post/form.html
  src/main/resources/templates/post/postDetail.html
  src/test/java/kr/codesqaud/cafe/account/UserControllerTest.java
  src/test/java/kr/codesqaud/cafe/post/PostControllerTest.java
Labels: documentation, step-1, step-2

#29 [지안] step-1 구현
  .gitignore
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/HomeController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/UserForm.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/qna/form.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/layout/navbar.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/test/java/kr/codesqaud/cafe/repository/MemoryUserRepositoryTest.java
  src/test/java/kr/codesqaud/cafe/service/UserServiceTest.java
Labels: documentation, step-1

#12 [네모네모] HTML 중복 제거
  ISSUE.md
  README.md
  REQUIREMENT.md
  STUDY_PLAN.md
  build.gradle
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/list.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/fragments/commonHead.html
  src/main/resources/templates/fragments/commonHeader.html
  src/main/resources/templates/fragments/commonScript.html
  src/main/resources/templates/fragments/commonSubnav.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/defaultLayout.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
Labels: documentation, step-1

#33 [Fia] step-1 / step-2 구현
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/resources/static/css/font.css
  src/main/resources/static/css/header.css
  src/main/resources/static/css/join.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/post.css
  src/main/resources/static/css/styles.css
  src/main/resources/static/index.html
  src/main/resources/static/js/validation.js
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/list.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/article/form.html
  src/main/resources/templates/article/list.html
  src/main/resources/templates/article/main.html
  src/main/resources/templates/article/show.html
  src/main/resources/templates/fragments/config.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/layout.html
  src/main/resources/templates/fragments/scripts.html
  src/main/resources/templates/index.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/join.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/update.html
  src/test/java/kr/codesqaud/cafe/repository/MemoryArticleRepositoryTest.java
  src/test/java/kr/codesqaud/cafe/repository/MemoryUserRepositoryTest.java
Labels: documentation, step-1, step-2

#3 [Joy] step-1/step2 구현
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/HomeController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/dto/ArticleForm.java
  src/main/java/kr/codesqaud/cafe/dto/UserForm.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/default_layout.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
Labels: step-1, step-2

#4 [sully] HTML 코드 중복 제거 / 회원 가입 / 회원 목록 조회 / 회원 프로필 정보 조회 / 게시글 작성 / 게시글 목록 조회 / 게시글 상세 조회 / 회원 정보 수정 화면
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/dto/ArticleForm.java
  src/main/java/kr/codesqaud/cafe/controller/dto/UserForm.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/list.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/duplicates/footer.html
  src/main/resources/templates/duplicates/header.html
  src/main/resources/templates/duplicates/navbar-fixed-top.html
  src/main/resources/templates/duplicates/subnav.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/updateForm.html
Labels: documentation, step-1, step-2

#42 [위즈] 스프링 카페 미션 - step-1, 2 구현
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/UserConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/dto/ArticleDto.java
  src/main/java/kr/codesqaud/cafe/dto/UserDto.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleFormRepository.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserFormRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/css/style.css
  src/main/resources/static/css/styles.css
  src/main/resources/static/favicon.ico
  src/main/resources/static/images/mail.png
  src/main/resources/static/images/menu-bar.png
  src/main/resources/static/images/profile_picture.jpg
  src/main/resources/static/index.html
  src/main/resources/static/js/dataValidation.js
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/list.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/detail.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/updateForm.html
Labels: step-1, step-2

#39 [나그] step -1 구현
  March5thStudyPlan.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/user/User.java
  src/main/java/kr/codesqaud/cafe/user/UserController.java
  src/main/java/kr/codesqaud/cafe/user/UserForm.java
  src/main/java/kr/codesqaud/cafe/user/UserRepository.java
  src/main/java/kr/codesqaud/cafe/user/UserService.java
  src/main/resources/application.properties
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/test/java/kr/codesqaud/cafe/UserRepositoryTest.java
Labels: step-1

#2 [나그]: 3월 5주차 학습계획서 작성
  March5thStudyPlan.md
Labels: documentation

#34 [길사] 1단계, 2단계 구현
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/config/RepositoryConfig.java
  src/main/java/kr/codesqaud/cafe/controller/PostController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Post.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/dto/PostDetailResponse.java
  src/main/java/kr/codesqaud/cafe/dto/PostListResponse.java
  src/main/java/kr/codesqaud/cafe/dto/PostWriteRequest.java
  src/main/java/kr/codesqaud/cafe/dto/UserListResponse.java
  src/main/java/kr/codesqaud/cafe/dto/UserProfileResponse.java
  src/main/java/kr/codesqaud/cafe/dto/UserRegisterRequest.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryPostRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/PostRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/PostService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/users/list.html
  src/main/resources/templates/users/login.html
  src/main/resources/templates/users/login_failed.html
  src/main/resources/templates/users/profile.html
  src/main/resources/templates/users/register.html
Labels: documentation, enhancement

#47 [GGOM] Step-1 회원가입, 회원목록 조회, 회원프로필 조회 기능 구현
  Misson.md
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/Service/MemberService.java
  src/main/java/kr/codesqaud/cafe/SpringConfiguration.java
  src/main/java/kr/codesqaud/cafe/controller/HomeController.java
  src/main/java/kr/codesqaud/cafe/controller/MemberController.java
  src/main/java/kr/codesqaud/cafe/controller/MemberForm.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Member.java
  src/main/java/kr/codesqaud/cafe/memory/MemberRepository.java
  src/main/java/kr/codesqaud/cafe/memory/MemoryMemberRepository.java
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
Labels: step-1

#7 [JAJA] step-1 feat
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/CafeApplication.java
  src/main/java/kr/codesqaud/cafe/controller/FormController.java
  src/main/resources/application.properties
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/css/styles.css
  src/main/resources/static/favicon.ico
  src/main/resources/static/fonts/glyphicons-halflings-regular.eot
  src/main/resources/static/fonts/glyphicons-halflings-regular.svg
  src/main/resources/static/fonts/glyphicons-halflings-regular.ttf
  src/main/resources/static/fonts/glyphicons-halflings-regular.woff
  src/main/resources/static/fonts/glyphicons-halflings-regular.woff2
  src/main/resources/static/images/80-text.png
  src/main/resources/static/index.html
  src/main/resources/static/js/bootstrap.min.js
  src/main/resources/static/js/jquery-2.2.0.min.js
  src/main/resources/static/js/scripts.js
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/list.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/form.html
  src/main/resources/templates/index.html
Labels: documentation, enhancement, step-1

#50 [차차] Step1 회원 가입 및 회원 목록 조회 기능
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/ExceptionHandlerController.java
  src/main/java/kr/codesqaud/cafe/controller/MemberController.java
  src/main/java/kr/codesqaud/cafe/domain/Member.java
  src/main/java/kr/codesqaud/cafe/dto/MemberResponseDto.java
  src/main/java/kr/codesqaud/cafe/dto/ProfileEditRequestDto.java
  src/main/java/kr/codesqaud/cafe/dto/SignUpRequestDto.java
  src/main/java/kr/codesqaud/cafe/repository/MemberRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryMemberRepository.java
  src/main/java/kr/codesqaud/cafe/service/MemberService.java
  src/main/resources/static/error/error.css
  src/main/resources/static/layout/layout.css
  src/main/resources/static/member/memberForm.css
  src/main/resources/static/member/members.css
  src/main/resources/templates/error/404.html
  src/main/resources/templates/error/4xx.html
  src/main/resources/templates/layout/head.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/member/members.html
  src/main/resources/templates/member/profile.html
  src/main/resources/templates/member/profileEdit.html
  src/main/resources/templates/member/signUp.html
  src/test/java/kr/codesqaud/cafe/controller/MemberControllerTest.java
  src/test/java/kr/codesqaud/cafe/service/MemberServiceTest.java
Labels: step-1

#46 [June] Cafe 1,2 단계 구현
  build.gradle
  src/main/java/kr/codesqaud/cafe/domain/article/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/domain/article/dto/request/ArticleSaveRequestDto.java
  src/main/java/kr/codesqaud/cafe/domain/article/dto/response/ArticleDetailResponseDto.java
  src/main/java/kr/codesqaud/cafe/domain/article/entity/Article.java
  src/main/java/kr/codesqaud/cafe/domain/article/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/domain/article/repository/impl/MemoryArticleRepositoryImpl.java
  src/main/java/kr/codesqaud/cafe/domain/user/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/user/dto/request/UserSaveRequestDto.java
  src/main/java/kr/codesqaud/cafe/domain/user/dto/request/UserUpdateRequestDto.java
  src/main/java/kr/codesqaud/cafe/domain/user/dto/response/UserDetailResponseDto.java
  src/main/java/kr/codesqaud/cafe/domain/user/entity/User.java
  src/main/java/kr/codesqaud/cafe/domain/user/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/domain/user/repository/impl/MemoryUserRepositoryImpl.java
  src/main/java/kr/codesqaud/cafe/global/config/MvcConfig.java
  src/main/resources/application.properties
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/css/index.css
  src/main/resources/static/css/post/form.css
  src/main/resources/static/css/post/show.css
  src/main/resources/static/css/reset.css
  src/main/resources/static/css/styles.css
  src/main/resources/static/css/user/form.css
  src/main/resources/static/css/user/list.css
  src/main/resources/static/css/user/login.css
  src/main/resources/static/css/user/login_success.css
  src/main/resources/static/css/user/profile.css
  src/main/resources/static/favicon.ico
  src/main/resources/static/fonts/glyphicons-halflings-regular.eot
  src/main/resources/static/fonts/glyphicons-halflings-regular.svg
  src/main/resources/static/fonts/glyphicons-halflings-regular.ttf
  src/main/resources/static/fonts/glyphicons-halflings-regular.woff
  src/main/resources/static/fonts/glyphicons-halflings-regular.woff2
  src/main/resources/static/images/80-text.png
  src/main/resources/static/images/KakaoCI.png
  src/main/resources/static/index.html
  src/main/resources/static/js/bootstrap.min.js
  src/main/resources/static/js/jquery-2.2.0.min.js
  src/main/resources/static/js/scripts.js
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/list.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/index.html
  src/main/resources/templates/post/form.html
  src/main/resources/templates/post/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_success.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/updateForm.html
Labels: step-1, step-2

#35 [브루니] 중복된 HTML 분리 / 회원 가입, 프로필 수정, 회원 목록 조회, 회원 프로필 조회기능 / 게시글 포스팅, 게시글 목록 조회, 게시글 상세내용 조회
  build.gradle
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/MainController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/dto/ArticleDto.java
  src/main/java/kr/codesqaud/cafe/controller/dto/UserDto.java
  src/main/java/kr/codesqaud/cafe/controller/dto/req/JoinRequest.java
  src/main/java/kr/codesqaud/cafe/controller/dto/req/PostingRequest.java
  src/main/java/kr/codesqaud/cafe/controller/dto/req/ProfileEditRequest.java
  src/main/java/kr/codesqaud/cafe/domain/article/Article.java
  src/main/java/kr/codesqaud/cafe/domain/user/User.java
  src/main/java/kr/codesqaud/cafe/exception/DuplicatedUserIdException.java
  src/main/java/kr/codesqaud/cafe/exception/GlobalExceptionHandler.java
  src/main/java/kr/codesqaud/cafe/exception/InvalidPasswordException.java
  src/main/java/kr/codesqaud/cafe/exception/NotFoundException.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/impl/ArticleMemoryRepository.java
  src/main/java/kr/codesqaud/cafe/repository/impl/UserMemoryRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/static/index.html
  src/main/resources/static/js/scripts.js
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/navigationbar.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/edit_form.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/notfound.html
  src/main/resources/templates/user/profile.html
  src/test/java/kr/codesqaud/cafe/service/ArticleServiceTest.java
  src/test/java/kr/codesqaud/cafe/service/UserServiceTest.java
Labels: enhancement, step-1, step-2

#18 [무비] 회원가입 및 회원 목록 조회 기능 + 글 쓰기 기능 구현
  build.gradle
  src/main/java/kr/codesqaud/cafe/Controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/Controller/UserController.java
  src/main/java/kr/codesqaud/cafe/Dto/ArticleDetailDto.java
  src/main/java/kr/codesqaud/cafe/Dto/ArticleFormDto.java
  src/main/java/kr/codesqaud/cafe/Dto/ArticleListDto.java
  src/main/java/kr/codesqaud/cafe/Dto/UserFormDto.java
  src/main/java/kr/codesqaud/cafe/Dto/UserListDto.java
  src/main/java/kr/codesqaud/cafe/Dto/UserProfileDto.java
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/index.html
  src/main/resources/static/qna/form.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/form.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/index.html
  src/main/resources/templates/partials/footer.html
  src/main/resources/templates/partials/header.html
  src/main/resources/templates/partials/navbar.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/test/java/kr/codesqaud/cafe/repository/MemoryArticleRepositoryTest.java
  src/test/java/kr/codesqaud/cafe/repository/MemoryUserRepositoryTest.java
  src/test/java/kr/codesqaud/cafe/service/ArticleServiceTest.java
  src/test/java/kr/codesqaud/cafe/service/UserServiceTest.java
Labels: step-1, step-2

#58 학습 계획 머지 스크립트 작성
  .github/workflows/auto-merge-study-plan.yml
  .github/workflows/pr-hello.yml
Labels: enhancement

#59 Honux plan
  .github/pull_request_template.md
  .github/workflows/auto-merge-study-plan.yml
  .github/workflows/automatic-merge.yml
  .github/workflows/pr-hello.yml
  README.md
Labels: study-plan

#60 자동 머지가 코멘트를 보내도록 로직 개선
  .github/workflows/auto-merge.yml
Labels: enhancement

#88 [파이] 사용자 정보 , 게시글 DB 저장 및 배포
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/dto/ArticleDto.java
  src/main/java/kr/codesqaud/cafe/controller/dto/PostingRequest.java
  src/main/java/kr/codesqaud/cafe/controller/dto/SignUpRequest.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/exception/DuplicatedUserIdException.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/schema.sql
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/layout/navbar.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
Labels: step-3

#94 [light] 미션 3단계 구현/배포 완료 , 1주차 코드리뷰 반영
  build.gradle
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/article/Article.java
  src/main/java/kr/codesqaud/cafe/domain/article/repository/ArticleJdbcImpl.java
  src/main/java/kr/codesqaud/cafe/domain/article/repository/ArticleMemoryImpl.java
  src/main/java/kr/codesqaud/cafe/domain/article/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/domain/member/UserMemoryImpl.java
  src/main/java/kr/codesqaud/cafe/domain/member/UserRepository.java
  src/main/java/kr/codesqaud/cafe/domain/question/ArticleMemoryImpl.java
  src/main/java/kr/codesqaud/cafe/domain/question/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/domain/user/User.java
  src/main/java/kr/codesqaud/cafe/domain/user/repository/UserJdbcImpl.java
  src/main/java/kr/codesqaud/cafe/domain/user/repository/UserMemoryImpl.java
  src/main/java/kr/codesqaud/cafe/domain/user/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/schema.sql
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/update_form.html
Labels: step-3

#87 [지안] step 1, 2, 3 구현
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleForm.java
  src/main/java/kr/codesqaud/cafe/controller/HomeController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/UserForm.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/schema.sql
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile.html
  src/test/java/kr/codesqaud/cafe/repository/MemoryUserRepositoryTest.java
  src/test/java/kr/codesqaud/cafe/repository/UserRepositoryTest.java
  src/test/java/kr/codesqaud/cafe/service/UserServiceTest.java
Labels: documentation, step-1, step-2, step-3

#89 [감귤] step 1-2
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/IndexController.java
  src/main/java/kr/codesqaud/cafe/controller/PostController.java
  src/main/java/kr/codesqaud/cafe/controller/PostForm.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/UserForm.java
  src/main/java/kr/codesqaud/cafe/domain/Post.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryPostRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/PostRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/PostService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/user/profile.html
  src/main/resources/templates/index.html
  src/main/resources/templates/post/form.html
  src/main/resources/templates/post/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
Labels: step-1, step-2

#96 [지구] Step-2 회원 정보 수정 구현 중
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/dto/ArticleDTO.java
  src/main/java/kr/codesqaud/cafe/controller/dto/UserReadDTO.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcTemplateArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcTemplateUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/schema.sql
  src/main/resources/static/css/post/show.css
  src/main/resources/templates/post/form.html
  src/main/resources/templates/post/modifyForm.html
  src/main/resources/templates/post/show.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/modifyProfile.html
  src/main/resources/templates/user/profile.html
Labels: step-2

#93 [bean] 게시글 기능, 데이터베이스 추가
  README.md
  WEEK1.md
  WEEK2.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/CafeApplication.java
  src/main/java/kr/codesqaud/cafe/common/exception/ExceptionControllerAdvice.java
  src/main/java/kr/codesqaud/cafe/common/exception/user/UserExceptionType.java
  src/main/java/kr/codesqaud/cafe/common/exception/user/UserFormInputException.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/ExceptionControllerAdvice.java
  src/main/java/kr/codesqaud/cafe/controller/HomeController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/dto/article/ArticleCreateDto.java
  src/main/java/kr/codesqaud/cafe/controller/dto/article/ArticleReadDto.java
  src/main/java/kr/codesqaud/cafe/controller/dto/user/UserFormDto.java
  src/main/java/kr/codesqaud/cafe/controller/dto/user/UserJoinDto.java
  src/main/java/kr/codesqaud/cafe/controller/dto/user/UserReadDto.java
  src/main/java/kr/codesqaud/cafe/controller/dto/user/UserUpdateDto.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/exception/user/UserJoinFailedException.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcArticleRepositoryImpl.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcUserRepositoryImpl.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepositoryImpl.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepositoryImpl.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/schema.sql
  src/main/resources/templates/article/form.html
  src/main/resources/templates/article/show.html
  src/main/resources/templates/error/error_page.html
  src/main/resources/templates/fragment/layout/nav.html
  src/main/resources/templates/home.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/update.html
  src/test/java/kr/codesqaud/cafe/controller/UserControllerTest.java
  src/test/java/kr/codesqaud/cafe/repository/PureUserRepositoryImplTest.java
  src/test/java/kr/codesqaud/cafe/service/UserServiceTest.java
Labels: enhancement, step-2, step-3

#92 [June] step-3 구현
  build.gradle
  src/main/java/kr/codesqaud/cafe/domain/article/entity/Article.java
  src/main/java/kr/codesqaud/cafe/domain/article/repository/impl/JdbcArticleRepositoryImpl.java
  src/main/java/kr/codesqaud/cafe/domain/article/repository/impl/MemoryArticleRepositoryImpl.java
  src/main/java/kr/codesqaud/cafe/domain/user/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/user/entity/User.java
  src/main/java/kr/codesqaud/cafe/domain/user/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/domain/user/repository/impl/JdbcUserRepositoryImpl.java
  src/main/java/kr/codesqaud/cafe/domain/user/repository/impl/MemoryUserRepositoryImpl.java
  src/main/resources/application.yml
  src/main/resources/schema.sql
Labels: step-3

#101 [만두] 3단계 구현
  README.md
  build.gradle
  deploy.sh
  src/main/java/kr/codesqaud/cafe/config/AppConfig.java
  src/main/java/kr/codesqaud/cafe/config/GlobalExceptionHandler.java
  src/main/java/kr/codesqaud/cafe/controller/MemberController.java
  src/main/java/kr/codesqaud/cafe/controller/PostController.java
  src/main/java/kr/codesqaud/cafe/domain/Member.java
  src/main/java/kr/codesqaud/cafe/domain/Post.java
  src/main/java/kr/codesqaud/cafe/dto/member/ProfileEditRequest.java
  src/main/java/kr/codesqaud/cafe/dto/member/SignUpRequest.java
  src/main/java/kr/codesqaud/cafe/dto/post/PostResponse.java
  src/main/java/kr/codesqaud/cafe/dto/post/PostWriteRequest.java
  src/main/java/kr/codesqaud/cafe/dto/post/WriterResponse.java
  src/main/java/kr/codesqaud/cafe/exception/common/BadRequestException.java
  src/main/java/kr/codesqaud/cafe/exception/common/BadRequestExceptionCode.java
  src/main/java/kr/codesqaud/cafe/exception/common/ErrorCodeNotFoundException.java
  src/main/java/kr/codesqaud/cafe/exception/common/NotFoundException.java
  src/main/java/kr/codesqaud/cafe/exception/controller/ExceptionController.java
  src/main/java/kr/codesqaud/cafe/exception/member/DuplicateMemberEmailException.java
  src/main/java/kr/codesqaud/cafe/exception/member/DuplicateMemberIdException.java
  src/main/java/kr/codesqaud/cafe/exception/member/MemberNotFoundException.java
  src/main/java/kr/codesqaud/cafe/exception/member/NotMatchMemberPassword.java
  src/main/java/kr/codesqaud/cafe/exception/post/PostNotFoundException.java
  src/main/java/kr/codesqaud/cafe/repository/member/JdbcMemberRepository.java
  src/main/java/kr/codesqaud/cafe/repository/member/MemoryMemberRepository.java
  src/main/java/kr/codesqaud/cafe/repository/post/JdbcPostRepository.java
  src/main/java/kr/codesqaud/cafe/repository/post/MemoryPostRepository.java
  src/main/java/kr/codesqaud/cafe/repository/post/PostRepository.java
  src/main/java/kr/codesqaud/cafe/service/MemberService.java
  src/main/java/kr/codesqaud/cafe/service/PostService.java
  src/main/resources/application.yml
  src/main/resources/errorMessages.properties
  src/main/resources/schema.sql
  src/main/resources/templates/error/400.html
  src/main/resources/templates/member/profileEdit.html
  src/main/resources/templates/member/signUp.html
  src/main/resources/templates/post/posts.html
  src/test/java/kr/codesqaud/annotation/RepositoryTest.java
  src/test/java/kr/codesqaud/cafe/CafeApplicationTests.java
  src/test/java/kr/codesqaud/cafe/controller/MemberControllerTest.java
  src/test/java/kr/codesqaud/cafe/controller/PostControllerTest.java
  src/test/java/kr/codesqaud/cafe/repository/member/MemberRepositoryTest.java
  src/test/java/kr/codesqaud/cafe/repository/post/PostRepositoryTest.java
  src/test/java/kr/codesqaud/cafe/service/MemberServiceTest.java
  src/test/java/kr/codesqaud/cafe/service/PostServiceTest.java
Labels: step-3

#56 [sully] H2 DB 연동 / Ec2 배포 / 회원 수정 기능 / DTO 재적용 / 시간 추가
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/dto/article/ArticleForm.java
  src/main/java/kr/codesqaud/cafe/controller/dto/article/ArticleTimeForm.java
  src/main/java/kr/codesqaud/cafe/controller/dto/user/UserForm.java
  src/main/java/kr/codesqaud/cafe/controller/dto/user/UserProfileForm.java
  src/main/java/kr/codesqaud/cafe/controller/dto/user/UserUpdateForm.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/article/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/article/JdbcTemplateArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/user/JdbcTemplateUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/user/UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/schema.sql
  src/main/resources/templates/error/4xx.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/updateForm.html
Labels: documentation, step-2, step-3

#95 [Joy] step-3 구현
  3월5주차_학습계획.md
  4월1주차_학습계획.md
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcTemplateArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcTemplateUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/schema.sql
  src/main/resources/templates/error/500.html
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/show.html
  src/test/java/kr/codesqaud/cafe/repository/JdbcUserRepositoryTest.java
Labels: step-3

#57 [브루니] H2 DB에 회원과 게시글 저장 / EC2 배포
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/domain/article/Article.java
  src/main/java/kr/codesqaud/cafe/domain/user/User.java
  src/main/java/kr/codesqaud/cafe/exception/GlobalExceptionHandler.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/impl/ArticleJdbcRepository.java
  src/main/java/kr/codesqaud/cafe/repository/impl/ArticleMemoryRepository.java
  src/main/java/kr/codesqaud/cafe/repository/impl/UserJdbcRepository.java
  src/main/java/kr/codesqaud/cafe/repository/impl/UserMemoryRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/schema.sql
  src/main/resources/templates/error.html
  src/main/resources/templates/fragments/navigationbar.html
  src/main/resources/templates/index.html
  src/main/resources/templates/user/edit_form.html
Labels: step-3

#100 [시오] 글 쓰기, 글 목록 조회, 게시글 상세 보기, 사용자 정보 수정/ H2 DB에 회원과 게시글 저장 / EC2 배포
  README.md
  build.gradle
  plan/week01.md
  plan/week02.md
  src/main/java/codesquad/cafe/controller/UserController.java
  src/main/java/codesquad/cafe/domain/article/controller/ArticleController.java
  src/main/java/codesquad/cafe/domain/article/domain/Article.java
  src/main/java/codesquad/cafe/domain/article/dto/ArticleRequestDto.java
  src/main/java/codesquad/cafe/domain/article/dto/ArticleResponseDto.java
  src/main/java/codesquad/cafe/domain/article/repository/ArticleRepository.java
  src/main/java/codesquad/cafe/domain/article/repository/JdbcTemplateArticleRepository.java
  src/main/java/codesquad/cafe/domain/article/repository/MemoryArticleRepository.java
  src/main/java/codesquad/cafe/domain/article/service/ArticleService.java
  src/main/java/codesquad/cafe/domain/user/controller/UserController.java
  src/main/java/codesquad/cafe/domain/user/domain/User.java
  src/main/java/codesquad/cafe/domain/user/dto/UserRequestDto.java
  src/main/java/codesquad/cafe/domain/user/dto/UserResponseDto.java
  src/main/java/codesquad/cafe/domain/user/dto/UserUpdateRequestDto.java
  src/main/java/codesquad/cafe/domain/user/repository/JdbcUserRepository.java
  src/main/java/codesquad/cafe/domain/user/repository/MemoryUserRepository.java
  src/main/java/codesquad/cafe/domain/user/repository/UserRepository.java
  src/main/java/codesquad/cafe/domain/user/service/UserService.java
  src/main/java/codesquad/cafe/dto/UserRequestDto.java
  src/main/java/codesquad/cafe/global/config/MvcConfig.java
  src/main/java/codesquad/cafe/repository/UserRepositoryImpl.java
  src/main/java/codesquad/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/schema.sql
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/fragments/user_navigation.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/updateForm.html
  src/test/java/codesquad/cafe/domain/article/controller/ArticleControllerTest.java
  src/test/java/codesquad/cafe/domain/article/repository/MemoryArticleRepositoryTest.java
  src/test/java/codesquad/cafe/domain/user/controller/UserControllerTest.java
  src/test/java/codesquad/cafe/domain/user/repository/UserRepositoryTest.java
  src/test/java/codesquad/cafe/domain/user/service/UserServiceTest.java
Labels: step-2, step-3

#63 [Ape] Step1 & Step-2
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/HomeController.java
  src/main/java/kr/codesqaud/cafe/controller/QuestionController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/PageHandler.java
  src/main/java/kr/codesqaud/cafe/domain/Question.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/dto/ErrorMessageDTO.java
  src/main/java/kr/codesqaud/cafe/dto/QuestionBoardDTO.java
  src/main/java/kr/codesqaud/cafe/dto/QuestionDetailsDTO.java
  src/main/java/kr/codesqaud/cafe/dto/QuestionTitleDTO.java
  src/main/java/kr/codesqaud/cafe/dto/QuestionWriteDTO.java
  src/main/java/kr/codesqaud/cafe/dto/SignUpDTO.java
  src/main/java/kr/codesqaud/cafe/dto/UserDTO.java
  src/main/java/kr/codesqaud/cafe/dummy/CollectionFrameworkRepositoryDummyData.java
  src/main/java/kr/codesqaud/cafe/repository/QuestionRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/QuestionService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/templates/user/form.mustache
  src/test/java/kr/codesqaud/cafe/domain/PageHandlerTest.java
Labels: step-1, step-2

#107 [소나무] Step2
  README.md
  src/main/java/kr/codesqaud/cafe/Repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/config/MvcConfiguration.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/templates/fragment/footer.html
  src/main/resources/templates/fragment/head.html
  src/main/resources/templates/fragment/nav.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile.html
Labels: step-2

#54 [JAJA] step-1 회원가입
  README.md
  src/main/java/kr/codesqaud/cafe/User.java
  src/main/java/kr/codesqaud/cafe/UserController.java
  src/main/java/kr/codesqaud/cafe/UserRepository.java
  src/main/java/kr/codesqaud/cafe/UserService.java
  src/main/java/kr/codesqaud/cafe/controller/FormController.java
  src/main/resources/application.properties
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/css/styles.css
  src/main/resources/static/favicon.ico
  src/main/resources/static/fonts/glyphicons-halflings-regular.eot
  src/main/resources/static/fonts/glyphicons-halflings-regular.svg
  src/main/resources/static/fonts/glyphicons-halflings-regular.ttf
  src/main/resources/static/fonts/glyphicons-halflings-regular.woff
  src/main/resources/static/fonts/glyphicons-halflings-regular.woff2
  src/main/resources/static/images/80-text.png
  src/main/resources/static/js/bootstrap.min.js
  src/main/resources/static/js/jquery-2.2.0.min.js
  src/main/resources/static/js/scripts.js
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/main/resources/static/user/profile.html
  src/main/resources/templates/form.html
  src/main/resources/templates/index.html
  src/main/resources/templates/list.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
Labels: step-1

#90 [Jinny] 스프링 카페 미션 - 3단계 구현
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/DTO/UserDTO.java
  src/main/java/kr/codesqaud/cafe/GlobalExceptionHandler.java
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/exception/signUpException/IllegalSignUpStateException.java
  src/main/java/kr/codesqaud/cafe/exception/signUpException/InvalidUserIdException.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepositoryImpl.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepositoryImpl.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/scheme.sql
  src/main/resources/templates/error.html
  src/main/resources/templates/index.html
Labels: step-3

#102 [위즈] Step-3 DB에 저장하기
  build.gradle
  src/main/java/kr/codesqaud/cafe/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/UserConfig.java
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/config/UserConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/dto/ArticleDto.java
  src/main/java/kr/codesqaud/cafe/dto/UserDto.java
  src/main/java/kr/codesqaud/cafe/exception/DuplicateUserException.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleFormRepository.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserFormRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/sql/schema.sql
  src/main/resources/static/js/dataValidation.js
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/detail.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/updateForm.html
Labels: step-3

#141 [나그] DB연동, 로그인 기능 구현
  src/main/java/kr/codesqaud/cafe/controller/LoginController.java
  src/main/java/kr/codesqaud/cafe/domain/LoginForm.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/LoginService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/static/qna/fake-1.html
  src/main/resources/static/qna/fake-2.html
  src/main/resources/static/qna/show.html
  src/main/resources/static/user/login.html
  src/main/resources/templates/fragments/navbar-default.html
  src/main/resources/templates/user/login.html
  src/test/java/kr/codesqaud/cafe/MemoryUserRepositoryTest.java
Labels: step-3, step-4

#124 [지안] step-3 aws ec2 배포, 피드백 수정
  src/main/java/kr/codesqaud/cafe/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/HomeController.java
  src/main/java/kr/codesqaud/cafe/controller/article/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/article/ArticleForm.java
  src/main/java/kr/codesqaud/cafe/controller/user/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/user/UserForm.java
  src/main/java/kr/codesqaud/cafe/controller/user/UserResponse.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/article/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/article/JdbcArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/article/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/user/JdbcUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/user/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/user/UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/main/resources/templates/layout/navbar.html
  src/main/resources/templates/user/form.html
  src/test/java/kr/codesqaud/cafe/repository/UserRepositoryTest.java
  src/test/java/kr/codesqaud/cafe/service/UserServiceTest.java
Labels: step-3

#150 [시오] step3 리팩토링
  build.gradle
  plan/week03.md
  src/main/java/codesquad/cafe/domain/article/controller/ArticleController.java
  src/main/java/codesquad/cafe/domain/article/domain/Article.java
  src/main/java/codesquad/cafe/domain/article/dto/ArticleRequestDto.java
  src/main/java/codesquad/cafe/domain/article/dto/ArticleResponseDto.java
  src/main/java/codesquad/cafe/domain/article/repository/JdbcTemplateArticleRepository.java
  src/main/java/codesquad/cafe/domain/user/controller/UserController.java
  src/main/java/codesquad/cafe/domain/user/service/UserService.java
  src/main/java/codesquad/cafe/global/exception/CustomException.java
  src/main/java/codesquad/cafe/global/exception/ErrorCode.java
  src/main/java/codesquad/cafe/global/exception/ErrorResponse.java
  src/main/java/codesquad/cafe/global/exception/GlobalExceptionHandler.java
  src/main/resources/application.properties
  src/main/resources/schema.sql
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/show.html
  src/test/java/codesquad/cafe/domain/article/repository/MemoryArticleRepositoryTest.java
Labels: enhancement, step-3

#142 [bean] 로그인 기능 구현
  README.md
  WEEK3.md
  src/main/java/kr/codesqaud/cafe/common/auth/LoginConfig.java
  src/main/java/kr/codesqaud/cafe/common/auth/LoginInterceptor.java
  src/main/java/kr/codesqaud/cafe/common/exception/CommonException.java
  src/main/java/kr/codesqaud/cafe/common/exception/CommonExceptionType.java
  src/main/java/kr/codesqaud/cafe/common/exception/ExceptionControllerAdvice.java
  src/main/java/kr/codesqaud/cafe/common/exception/user/UserExceptionType.java
  src/main/java/kr/codesqaud/cafe/common/exception/user/UserFormInputException.java
  src/main/java/kr/codesqaud/cafe/common/exception/user/UserJoinException.java
  src/main/java/kr/codesqaud/cafe/common/exception/user/UserLoginException.java
  src/main/java/kr/codesqaud/cafe/common/exception/user/UserUpdateException.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/dto/article/ArticleCreateDto.java
  src/main/java/kr/codesqaud/cafe/controller/dto/user/LoginUserSession.java
  src/main/java/kr/codesqaud/cafe/controller/dto/user/UserFormDto.java
  src/main/java/kr/codesqaud/cafe/controller/dto/user/UserJoinDto.java
  src/main/java/kr/codesqaud/cafe/controller/dto/user/UserLoginDto.java
  src/main/java/kr/codesqaud/cafe/controller/dto/user/UserUpdateDto.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcArticleRepositoryImpl.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcUserRepositoryImpl.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/schema.sql
  src/main/resources/templates/article/form.html
  src/main/resources/templates/fragment/layout/nav.html
  src/main/resources/templates/home.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/test/java/kr/codesqaud/cafe/controller/UserControllerTest.java
  src/test/java/kr/codesqaud/cafe/repository/PureUserRepositoryImplTest.java
  src/test/java/kr/codesqaud/cafe/service/UserServiceTest.java
Labels: step-4

#134 [Hana] step-3
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/article/Article.java
  src/main/java/kr/codesqaud/cafe/article/ArticleDTO.java
  src/main/java/kr/codesqaud/cafe/article/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/article/H2ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/article/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/HomeController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/user/H2UserRepository.java
  src/main/java/kr/codesqaud/cafe/user/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/schema.sql
  src/main/resources/templates/qna/detail.html
Labels: step-3

#145 [JAJA] step-1 구현
  README.md
  src/main/java/kr/codesqaud/cafe/UserController.java
  src/main/java/kr/codesqaud/cafe/UserRepository.java
  src/main/java/kr/codesqaud/cafe/UserService.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/templates/index.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/profile.html
Labels: step-1

#128 [네모네모] step-3 구현
  README.md
  build.gradle
  deploy.sh
  src/main/java/kr/codesqaud/cafe/domain/article/Article.java
  src/main/java/kr/codesqaud/cafe/domain/article/ArticleJdbcRepository.java
  src/main/java/kr/codesqaud/cafe/domain/article/ArticleMemoryRepository.java
  src/main/java/kr/codesqaud/cafe/domain/article/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/domain/user/User.java
  src/main/java/kr/codesqaud/cafe/domain/user/UserJdbcRepository.java
  src/main/java/kr/codesqaud/cafe/domain/user/UserMemoryRepository.java
  src/main/java/kr/codesqaud/cafe/domain/user/UserRepository.java
  src/main/java/kr/codesqaud/cafe/web/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/web/dto/article/ArticleResponseDto.java
  src/main/java/kr/codesqaud/cafe/web/dto/article/ArticleSavedRequestDto.java
  src/main/java/kr/codesqaud/cafe/web/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/web/service/UserService.java
  src/main/java/kr/codesqaud/cafe/web/validator/UserValidator.java
  src/main/resources/application.properties
  src/main/resources/db/h2/data.sql
  src/main/resources/db/h2/schema.sql
  src/main/resources/static/js/user/updateForm.js
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/detail.html
  src/main/resources/templates/user/updateForm.html
  src/test/java/kr/codesqaud/cafe/web/controller/ArticleControllerTest.java
  src/test/java/kr/codesqaud/cafe/web/controller/UserControllerTest.java
Labels: step-3

#140 [위즈] 스프링 카페3 Step-4: 로그인, step-5: 게시글 권한부여
  README.md
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/config/UserConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleCommandController.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleQueryController.java
  src/main/java/kr/codesqaud/cafe/controller/UserCommandController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/UserQueryController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/exception/DuplicateUserException.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleFormRepository.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleSql.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserFormRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserSql.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/css/style.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/detail.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/updateDetail.html
  src/main/resources/templates/user/checkForUpdate.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/updateForm.html
Labels: step-4, step-5

#131 [만두] 4,5단계 구현
  README.md
  deploy.sh
  src/main/java/kr/codesqaud/cafe/config/AppConfig.java
  src/main/java/kr/codesqaud/cafe/config/GlobalExceptionHandler.java
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/config/SignInArgumentResolver.java
  src/main/java/kr/codesqaud/cafe/config/SignInInterceptor.java
  src/main/java/kr/codesqaud/cafe/config/session/AccountSession.java
  src/main/java/kr/codesqaud/cafe/config/session/SignIn.java
  src/main/java/kr/codesqaud/cafe/controller/MemberController.java
  src/main/java/kr/codesqaud/cafe/controller/PostController.java
  src/main/java/kr/codesqaud/cafe/domain/Member.java
  src/main/java/kr/codesqaud/cafe/domain/Post.java
  src/main/java/kr/codesqaud/cafe/dto/member/ProfileEditRequest.java
  src/main/java/kr/codesqaud/cafe/dto/member/SignInRequest.java
  src/main/java/kr/codesqaud/cafe/dto/member/SignUpRequest.java
  src/main/java/kr/codesqaud/cafe/dto/post/PostModifyRequest.java
  src/main/java/kr/codesqaud/cafe/dto/post/PostResponse.java
  src/main/java/kr/codesqaud/cafe/dto/post/PostWriteRequest.java
  src/main/java/kr/codesqaud/cafe/exception/common/Unauthorized.java
  src/main/java/kr/codesqaud/cafe/repository/member/JdbcMemberRepository.java
  src/main/java/kr/codesqaud/cafe/repository/member/MemoryMemberRepository.java
  src/main/java/kr/codesqaud/cafe/repository/post/JdbcPostRepository.java
  src/main/java/kr/codesqaud/cafe/repository/post/MemoryPostRepository.java
  src/main/java/kr/codesqaud/cafe/repository/post/PostRepository.java
  src/main/java/kr/codesqaud/cafe/service/MemberService.java
  src/main/java/kr/codesqaud/cafe/service/PostService.java
  src/main/java/kr/codesqaud/cafe/util/SignInSessionUtil.java
  src/main/java/kr/codesqaud/cafe/validator/ProfileEditRequestValidator.java
  src/main/java/kr/codesqaud/cafe/validator/SignInRequestValidator.java
  src/main/java/kr/codesqaud/cafe/validator/SignUpRequestValidator.java
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/main/resources/errorMessages.properties
  src/main/resources/schema.sql
  src/main/resources/static/css/member/memberForm.css
  src/main/resources/static/css/post/post.css
  src/main/resources/static/css/post/write.css
  src/main/resources/templates/error/4xx.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/member/profile.html
  src/main/resources/templates/member/profileEdit.html
  src/main/resources/templates/member/signIn.html
  src/main/resources/templates/member/signUp.html
  src/main/resources/templates/post/post.html
  src/main/resources/templates/post/postModify.html
  src/main/resources/templates/post/postWrite.html
  src/test/java/kr/codesqaud/cafe/controller/MemberControllerTest.java
  src/test/java/kr/codesqaud/cafe/controller/PostControllerTest.java
  src/test/java/kr/codesqaud/cafe/repository/member/MemberRepositoryTest.java
  src/test/java/kr/codesqaud/cafe/repository/post/PostRepositoryTest.java
  src/test/java/kr/codesqaud/cafe/service/MemberServiceTest.java
  src/test/java/kr/codesqaud/cafe/service/PostServiceTest.java
Labels: step-4, step-5

#133 [소나무] Step3 H2 DB연동, 게시글 데이터 저장, 목록구현, 상세보기 구현, 사용자 정보 DB 저장
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/Repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/Repository/article/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/Repository/article/JdbcArticleRepository.java
  src/main/java/kr/codesqaud/cafe/Repository/article/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/Repository/user/JdbcUserRepository.java
  src/main/java/kr/codesqaud/cafe/Repository/user/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/Repository/user/UserRepository.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/dto/article/ArticleRequestDto.java
  src/main/java/kr/codesqaud/cafe/dto/article/ArticleResponseDto.java
  src/main/java/kr/codesqaud/cafe/dto/user/UserRequestDto.java
  src/main/java/kr/codesqaud/cafe/dto/user/UserResponseDto.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/schema.sql
  src/main/resources/templates/index.html
  src/main/resources/templates/user/form.html
Labels: step-3

#132 [takealook] Step-3 DB 연결
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/MainController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/dto/ArticleDto.java
  src/main/java/kr/codesqaud/cafe/controller/dto/request/PostRequest.java
  src/main/java/kr/codesqaud/cafe/controller/dto/request/ProfileEditRequest.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/schema.sql
  src/main/resources/static/favicon.ico
  src/main/resources/static/fonts/glyphicons-halflings-regular.eot
  src/main/resources/static/fonts/glyphicons-halflings-regular.ttf
  src/main/resources/static/fonts/glyphicons-halflings-regular.woff
  src/main/resources/static/fonts/glyphicons-halflings-regular.woff2
  src/main/resources/static/images/80-text.png
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/edit_form.html
  src/main/resources/templates/user/list.html
  step1-README.md
  step2-README.md
  step3-README.md
Labels: step-2, step-3

#130 [무비] 로그인 & 게시글 작성, 수정 구현
  build.gradle
  src/main/java/kr/codesqaud/cafe/article/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/article/domain/Article.java
  src/main/java/kr/codesqaud/cafe/article/dto/ArticleDetailDto.java
  src/main/java/kr/codesqaud/cafe/article/dto/ArticleFormDto.java
  src/main/java/kr/codesqaud/cafe/article/dto/ArticlePreviewDto.java
  src/main/java/kr/codesqaud/cafe/article/mapper/ArticleDtoMapper.java
  src/main/java/kr/codesqaud/cafe/article/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/article/repository/JdbcArticleRepository.java
  src/main/java/kr/codesqaud/cafe/article/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/article/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/user/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/user/dto/UserPreviewDto.java
  src/main/java/kr/codesqaud/cafe/user/dto/UserProfileDto.java
  src/main/java/kr/codesqaud/cafe/user/mapper/UserDtoMapper.java
  src/main/java/kr/codesqaud/cafe/user/repository/JdbcUserRepository.java
  src/main/java/kr/codesqaud/cafe/user/repository/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/user/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/user/service/UserService.java
  src/main/java/kr/codesqaud/cafe/utils/Session.java
  src/main/resources/application.properties
  src/main/resources/schema.sql
  src/main/resources/static/css/mystyle.css
  src/main/resources/static/js/homepage.js
  src/main/resources/static/js/registrationValidator.js
  src/main/resources/static/js/writerValidator.js
  src/main/resources/static/json-data/movieRecommendation.json
  src/main/resources/templates/articles/forbidden.mustache
  src/main/resources/templates/articles/list.mustache
  src/main/resources/templates/articles/modify-form.mustache
  src/main/resources/templates/articles/show-detail.mustache
  src/main/resources/templates/articles/write-form.mustache
  src/main/resources/templates/index.html
  src/main/resources/templates/index.mustache
  src/main/resources/templates/layout/footer.mustache
  src/main/resources/templates/layout/header.mustache
  src/main/resources/templates/partials/footer.html
  src/main/resources/templates/partials/header.html
  src/main/resources/templates/partials/navbar.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/list.mustache
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login.mustache
  src/main/resources/templates/user/login_failed.mustache
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/profile.mustache
  src/main/resources/templates/user/sign-up-form.mustache
  src/test/java/kr/codesqaud/cafe/repository/JdbcArticleRepositoryTest.java
  src/test/java/kr/codesqaud/cafe/repository/MemoryArticleRepositoryTest.java
  src/test/java/kr/codesqaud/cafe/repository/MemoryUserRepositoryTest.java
Labels: step-4, step-5

#148 [light] 미션 4단계 로그인,권한 / 미션 5단계 게시글 수정 삭제 / 검증,예외처리(미완성)
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/GlobalExceptionHandler.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/article/Article.java
  src/main/java/kr/codesqaud/cafe/domain/article/repository/ArticleJdbcImpl.java
  src/main/java/kr/codesqaud/cafe/domain/article/repository/ArticleJdbcRepository.java
  src/main/java/kr/codesqaud/cafe/domain/article/repository/ArticleMemoryRepository.java
  src/main/java/kr/codesqaud/cafe/domain/article/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/domain/user/User.java
  src/main/java/kr/codesqaud/cafe/domain/user/repository/UserJdbcRepository.java
  src/main/java/kr/codesqaud/cafe/domain/user/repository/UserMemoryRepository.java
  src/main/java/kr/codesqaud/cafe/domain/user/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/dto/ArticleFormDto.java
  src/main/java/kr/codesqaud/cafe/dto/LoginSessionDto.java
  src/main/java/kr/codesqaud/cafe/dto/SignUpFormDto.java
  src/main/java/kr/codesqaud/cafe/dto/UpdateFormDto.java
  src/main/java/kr/codesqaud/cafe/exception/DeniedAccessException.java
  src/main/java/kr/codesqaud/cafe/exception/DuplicatedIdException.java
  src/main/java/kr/codesqaud/cafe/exception/LoginFailedException.java
  src/main/java/kr/codesqaud/cafe/exception/NotFoundException.java
  src/main/java/kr/codesqaud/cafe/schema.sql
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/qna/update_form.html
  src/main/resources/templates/user/error.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/update_form.html
Labels: step-4, step-5

#187 [파이] 댓글 저장 / 삭제
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/CommentController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/dto/CommentDto.java
  src/main/java/kr/codesqaud/cafe/controller/dto/CommentRequest.java
  src/main/java/kr/codesqaud/cafe/domain/Comment.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/CommentRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcCommentRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcUserRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/CommentService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/schema.sql
  src/main/resources/templates/layout/navbar.html
  src/main/resources/templates/qna/edit_form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/modify_faild.html
Labels: step-6

#182 [sully] mysql 연동 / soft-delete / 댓글 작성, 삭제 / 댓글 수 카운트 / ajax 댓글 작성
  .gitignore
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/article/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/reply/ReplyController.java
  src/main/java/kr/codesqaud/cafe/controller/user/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/Reply.java
  src/main/java/kr/codesqaud/cafe/domain/dto/article/ArticleTimeForm.java
  src/main/java/kr/codesqaud/cafe/domain/dto/reply/ReplyForm.java
  src/main/java/kr/codesqaud/cafe/domain/dto/reply/ReplyTimeForm.java
  src/main/java/kr/codesqaud/cafe/domain/dto/user/UserUpdateForm.java
  src/main/java/kr/codesqaud/cafe/repository/article/JdbcTemplateArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/reply/JdbcTemplateReplyRepository.java
  src/main/java/kr/codesqaud/cafe/repository/reply/ReplyRepository.java
  src/main/java/kr/codesqaud/cafe/repository/user/JdbcTemplateUserRepository.java
  src/main/java/kr/codesqaud/cafe/service/article/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/reply/ReplyService.java
  src/main/java/kr/codesqaud/cafe/service/user/UserService.java
  src/main/resources/application.properties
  src/main/resources/schema.sql
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/duplicates/footer.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/qna/updateForm.html
  src/main/resources/templates/user/updateForm.html
Labels: step-6, step-7

#201 [Ape] Stpe-4 로그인 기능 구현
  build.gradle
  src/main/java/kr/codesqaud/cafe/common/aop/ControllerExceptionHandler.java
  src/main/java/kr/codesqaud/cafe/common/repository/CollectionFrameworkRepositoryDummyData.java
  src/main/java/kr/codesqaud/cafe/common/web/PageHandler.java
  src/main/java/kr/codesqaud/cafe/question/controller/QuestionController.java
  src/main/java/kr/codesqaud/cafe/question/controller/request/QuestionWriteRequestDTO.java
  src/main/java/kr/codesqaud/cafe/question/controller/response/QuestionBoardResponseDTO.java
  src/main/java/kr/codesqaud/cafe/question/controller/response/QuestionDetailDTO.java
  src/main/java/kr/codesqaud/cafe/question/controller/response/QuestionTitleResponseDTO.java
  src/main/java/kr/codesqaud/cafe/question/domain/Question.java
  src/main/java/kr/codesqaud/cafe/question/dto/response/QuestionBoardDTO.java
  src/main/java/kr/codesqaud/cafe/question/exception/QuestionNotExistException.java
  src/main/java/kr/codesqaud/cafe/question/repository/CollectionFrameWorkQuestionRepository.java
  src/main/java/kr/codesqaud/cafe/question/repository/H2QuestionRepository.java
  src/main/java/kr/codesqaud/cafe/question/repository/QuestionRepository.java
  src/main/java/kr/codesqaud/cafe/question/repository/TempQuestionTable.java
  src/main/java/kr/codesqaud/cafe/question/service/QuestionService.java
  src/main/java/kr/codesqaud/cafe/user/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/user/controller/request/SignInRequestDTO.java
  src/main/java/kr/codesqaud/cafe/user/controller/request/SignUpRequestDTO.java
  src/main/java/kr/codesqaud/cafe/user/controller/response/AuthSession.java
  src/main/java/kr/codesqaud/cafe/user/controller/response/UserResponseDTO.java
  src/main/java/kr/codesqaud/cafe/user/domain/User.java
  src/main/java/kr/codesqaud/cafe/user/dto/response/UserDTO.java
  src/main/java/kr/codesqaud/cafe/user/exception/UserDoesNotMatchException.java
  src/main/java/kr/codesqaud/cafe/user/exception/UserIdDuplicateException.java
  src/main/java/kr/codesqaud/cafe/user/exception/UserNotExistException.java
  src/main/java/kr/codesqaud/cafe/user/repository/CollectionFrameworkUserRepository.java
  src/main/java/kr/codesqaud/cafe/user/repository/H2UserRepository.java
  src/main/java/kr/codesqaud/cafe/user/repository/TempUserTable.java
  src/main/java/kr/codesqaud/cafe/user/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/user/service/UserService.java
  src/main/resources/schema.sql
  src/test/java/kr/codesqaud/cafe/common/domain/PageHandlerTest.java
  src/test/java/kr/codesqaud/cafe/question/QuestionControllerTest.java
  src/test/java/kr/codesqaud/cafe/question/QuestionServiceTest.java
Labels: step-4

#191 [June] 댓글 작성,삭제 기능 구현
  build.gradle
  src/main/java/kr/codesqaud/cafe/domain/article/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/domain/article/dto/request/ArticleSaveRequestDto.java
  src/main/java/kr/codesqaud/cafe/domain/article/dto/response/ArticleDetailResponseDto.java
  src/main/java/kr/codesqaud/cafe/domain/article/entity/Article.java
  src/main/java/kr/codesqaud/cafe/domain/article/repository/impl/JdbcArticleRepositoryImpl.java
  src/main/java/kr/codesqaud/cafe/domain/auth/controller/AuthController.java
  src/main/java/kr/codesqaud/cafe/domain/auth/dto/request/AuthLoginRequestDto.java
  src/main/java/kr/codesqaud/cafe/domain/reply/controller/ReplyController.java
  src/main/java/kr/codesqaud/cafe/domain/reply/dto/request/ReplySaveRequestDto.java
  src/main/java/kr/codesqaud/cafe/domain/reply/dto/response/ReplyDetailResponseDto.java
  src/main/java/kr/codesqaud/cafe/domain/reply/entity/Reply.java
  src/main/java/kr/codesqaud/cafe/domain/reply/repository/ReplyRepository.java
  src/main/java/kr/codesqaud/cafe/domain/reply/repository/impl/JdbcReplyRepositoryImpl.java
  src/main/java/kr/codesqaud/cafe/domain/user/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/user/dto/request/UserSaveRequestDto.java
  src/main/java/kr/codesqaud/cafe/domain/user/dto/request/UserUpdateRequestDto.java
  src/main/java/kr/codesqaud/cafe/domain/user/dto/response/UserDetailResponseDto.java
  src/main/java/kr/codesqaud/cafe/domain/user/entity/User.java
  src/main/java/kr/codesqaud/cafe/domain/user/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/domain/user/repository/impl/JdbcUserRepositoryImpl.java
  src/main/java/kr/codesqaud/cafe/domain/user/repository/impl/MemoryUserRepositoryImpl.java
  src/main/java/kr/codesqaud/cafe/global/common/constant/SessionAttributeNames.java
  src/main/java/kr/codesqaud/cafe/global/common/interceptor/LoginInterceptor.java
  src/main/java/kr/codesqaud/cafe/global/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/global/exception/GlobalExceptionHandler.java
  src/main/java/kr/codesqaud/cafe/global/exception/user/DuplicatedUserIdException.java
  src/main/java/kr/codesqaud/cafe/global/exception/user/InvalidLoginInfoException.java
  src/main/java/kr/codesqaud/cafe/global/exception/user/InvalidPasswordException.java
  src/main/resources/schema.sql
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/index.html
  src/main/resources/templates/post/form.html
  src/main/resources/templates/post/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/updateForm.html
  src/test/java/kr/codesqaud/cafe/largest/ArticleLargeTest.java
  src/test/java/kr/codesqaud/cafe/largest/ReplyLargeTest.java
  src/test/java/kr/codesqaud/cafe/largest/UserErrorLargeTest.java
  src/test/java/kr/codesqaud/cafe/largest/UserLargeTest.java
Labels: step-6

#204 [ light ] step-6 , step-7 구현 완료
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/GlobalExceptionHandler.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/article/Article.java
  src/main/java/kr/codesqaud/cafe/domain/article/repository/ArticleJdbcRepository.java
  src/main/java/kr/codesqaud/cafe/domain/article/repository/ArticleMemoryRepository.java
  src/main/java/kr/codesqaud/cafe/domain/reply/Reply.java
  src/main/java/kr/codesqaud/cafe/domain/reply/repository/ReplyMysqlRepository.java
  src/main/java/kr/codesqaud/cafe/domain/reply/repository/ReplyRepository.java
  src/main/java/kr/codesqaud/cafe/domain/user/User.java
  src/main/java/kr/codesqaud/cafe/domain/user/repository/UserJdbcRepository.java
  src/main/java/kr/codesqaud/cafe/domain/user/repository/UserMemoryRepository.java
  src/main/java/kr/codesqaud/cafe/domain/user/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/dto/LoginSessionDto.java
  src/main/java/kr/codesqaud/cafe/dto/SignUpFormDto.java
  src/main/java/kr/codesqaud/cafe/dto/UpdateFormDto.java
  src/main/java/kr/codesqaud/cafe/schema.sql
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/qna/update_form.html
  src/main/resources/templates/user/error.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/update_form.html
Labels: step-6, step-7

#200 [Jinny] 스프링 카페 미션 - 6단계 구현
  README.md
  autobuild.sh
  build.gradle
  src/main/java/kr/codesqaud/cafe/article/Article.java
  src/main/java/kr/codesqaud/cafe/article/ArticleController.java
  src/main/java/kr/codesqaud/cafe/article/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/article/ArticleRepositoryImpl.java
  src/main/java/kr/codesqaud/cafe/article/ArticleService.java
  src/main/java/kr/codesqaud/cafe/article/dto/ArticleRequestDto.java
  src/main/java/kr/codesqaud/cafe/article/dto/ArticleResponseDto.java
  src/main/java/kr/codesqaud/cafe/reply/Reply.java
  src/main/java/kr/codesqaud/cafe/reply/ReplyController.java
  src/main/java/kr/codesqaud/cafe/reply/ReplyRepository.java
  src/main/java/kr/codesqaud/cafe/reply/ReplyRepositoryImpl.java
  src/main/java/kr/codesqaud/cafe/reply/ReplyRequestDto.java
  src/main/java/kr/codesqaud/cafe/reply/ReplyResponseDto.java
  src/main/java/kr/codesqaud/cafe/reply/ReplyService.java
  src/main/resources/application.properties
  src/main/resources/scheme.sql
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/edit_form.html
  src/main/resources/templates/qna/show.html
  src/test/java/kr/codesqaud/cafe/repository/ArticleRepositoryImplTest.java
  src/test/java/kr/codesqaud/cafe/service/ArticleServiceTest.java
  src/test/resources/application.properties
  src/test/resources/scheme.sql
Labels: step-6

#192 [지구] - step 5 구현중
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/LoginController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/dto/ArticleDTO.java
  src/main/java/kr/codesqaud/cafe/controller/dto/ModifiedUserDTO.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcTemplateArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcTemplateUserRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/LoginService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/schema.sql
  src/main/resources/static/image/403-Forbidden-Page.gif
  src/main/resources/templates/error/forbidden403.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/nav.html
  src/main/resources/templates/login/form.html
  src/main/resources/templates/post/form.html
  src/main/resources/templates/post/modifyForm.html
  src/main/resources/templates/post/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/modifyProfile.html
  src/main/resources/templates/user/profile.html
Labels: step-5

#180 [브루니] 댓글 작성 / 삭제 구현
  .gitignore
  README.md
  build.gradle
  src/main/java/kr/codesqaud/cafe/common/interceptor/LoginInterceptor.java
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/CommentController.java
  src/main/java/kr/codesqaud/cafe/controller/MainController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/dto/ArticleDetails.java
  src/main/java/kr/codesqaud/cafe/controller/dto/ArticleParam.java
  src/main/java/kr/codesqaud/cafe/controller/dto/ArticleResponse.java
  src/main/java/kr/codesqaud/cafe/controller/dto/ArticleWithCommentCount.java
  src/main/java/kr/codesqaud/cafe/controller/dto/CommentResponse.java
  src/main/java/kr/codesqaud/cafe/controller/dto/CommentSaveResponse.java
  src/main/java/kr/codesqaud/cafe/controller/dto/req/CommentRequest.java
  src/main/java/kr/codesqaud/cafe/domain/article/Article.java
  src/main/java/kr/codesqaud/cafe/domain/comment/Comment.java
  src/main/java/kr/codesqaud/cafe/exception/BusinessException.java
  src/main/java/kr/codesqaud/cafe/exception/GlobalExceptionHandler.java
  src/main/java/kr/codesqaud/cafe/exception/InvalidOperationException.java
  src/main/java/kr/codesqaud/cafe/exception/InvalidSessionException.java
  src/main/java/kr/codesqaud/cafe/exception/NoAuthorizationException.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/CommentRepository.java
  src/main/java/kr/codesqaud/cafe/repository/impl/ArticleJdbcRepository.java
  src/main/java/kr/codesqaud/cafe/repository/impl/ArticleMemoryRepository.java
  src/main/java/kr/codesqaud/cafe/repository/impl/CommentJdbcRepository.java
  src/main/java/kr/codesqaud/cafe/repository/impl/UserJdbcRepository.java
  src/main/java/kr/codesqaud/cafe/repository/impl/UserMemoryRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/CommentService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/schema.sql
  src/main/resources/static/js/comment.js
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/test/java/kr/codesqaud/cafe/controller/ArticleControllerTest.java
  src/test/java/kr/codesqaud/cafe/controller/CommentControllerTest.java
  src/test/java/kr/codesqaud/cafe/controller/UserControllerTest.java
  src/test/java/kr/codesqaud/cafe/fixture/FixtureFactory.java
  src/test/java/kr/codesqaud/cafe/service/ArticleServiceTest.java
  src/test/java/kr/codesqaud/cafe/service/CommentServiceTest.java
  src/test/java/kr/codesqaud/cafe/service/UserServiceTest.java
Labels: step-6, step-7

#222 [Hana] step3 배포
  README.md
  src/main/java/kr/codesqaud/cafe/article/Article.java
  src/main/java/kr/codesqaud/cafe/article/ArticleDTO.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/user/H2UserRepository.java
  src/main/java/kr/codesqaud/cafe/user/MemoryUserRepository.java
  src/main/java/kr/codesqaud/cafe/user/UserDTO.java
  src/main/java/kr/codesqaud/cafe/user/UserRepository.java
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/detail.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/user/checkPassword.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/login_failed.html
  src/main/resources/templates/user/profile.html
  src/main/resources/templates/user/updateForm.html
Labels: step-3

#219 [sully] ajax 댓글 삭제 / 게시글 페이징
  build.gradle
  src/main/java/kr/codesqaud/cafe/config/SwaggerConfig.java
  src/main/java/kr/codesqaud/cafe/controller/article/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/reply/ReplyController.java
  src/main/java/kr/codesqaud/cafe/controller/user/LoginController.java
  src/main/java/kr/codesqaud/cafe/controller/user/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/Reply.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/domain/dto/Result.java
  src/main/java/kr/codesqaud/cafe/domain/dto/article/ArticleForm.java
  src/main/java/kr/codesqaud/cafe/domain/dto/article/ArticleTimeForm.java
  src/main/java/kr/codesqaud/cafe/domain/dto/article/ArticleUpdateForm.java
  src/main/java/kr/codesqaud/cafe/domain/dto/reply/ReplyForm.java
  src/main/java/kr/codesqaud/cafe/domain/dto/reply/ReplyTimeForm.java
  src/main/java/kr/codesqaud/cafe/domain/dto/user/UserForm.java
  src/main/java/kr/codesqaud/cafe/domain/dto/user/UserListForm.java
  src/main/java/kr/codesqaud/cafe/domain/dto/user/UserLoginForm.java
  src/main/java/kr/codesqaud/cafe/domain/dto/user/UserProfileForm.java
  src/main/java/kr/codesqaud/cafe/domain/dto/user/UserUpdateForm.java
  src/main/java/kr/codesqaud/cafe/domain/vo/PageForm.java
  src/main/java/kr/codesqaud/cafe/global/Tables.java
  src/main/java/kr/codesqaud/cafe/repository/article/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/article/JdbcTemplateArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/reply/JdbcTemplateReplyRepository.java
  src/main/java/kr/codesqaud/cafe/repository/user/JdbcTemplateUserRepository.java
  src/main/java/kr/codesqaud/cafe/service/article/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/reply/ReplyService.java
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/show.html
Labels: step-7, step-8

#226 [Joy] step7 댓글삭제/step8 페이징
  build.gradle
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/ReplyController.java
  src/main/java/kr/codesqaud/cafe/dto/SimpleArticle.java
  src/main/java/kr/codesqaud/cafe/pagination/Paging.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcTemplateArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/MemoryArticleRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/show.html
Labels: step-7, step-8

#231 [Ape] step-5,6,7,8
  src/main/java/kr/codesqaud/cafe/common/aop/ControllerExceptionHandler.java
  src/main/java/kr/codesqaud/cafe/common/auth/exception/NoAccessPermissionException.java
  src/main/java/kr/codesqaud/cafe/common/auth/exception/NoAuthSessionException.java
  src/main/java/kr/codesqaud/cafe/common/auth/utill/AuthSessionValidator.java
  src/main/java/kr/codesqaud/cafe/common/repository/CollectionFrameworkRepositoryDummyData.java
  src/main/java/kr/codesqaud/cafe/common/web/CursorPageHandler.java
  src/main/java/kr/codesqaud/cafe/common/web/PageHandler.java
  src/main/java/kr/codesqaud/cafe/question/controller/QuestionController.java
  src/main/java/kr/codesqaud/cafe/question/controller/request/QuestionWriteRequestDTO.java
  src/main/java/kr/codesqaud/cafe/question/controller/response/QuestionBoardResponseDTO.java
  src/main/java/kr/codesqaud/cafe/question/controller/response/QuestionDetailDTO.java
  src/main/java/kr/codesqaud/cafe/question/controller/response/QuestionDetailResponseDTO.java
  src/main/java/kr/codesqaud/cafe/question/controller/response/QuestionTitleResponseDTO.java
  src/main/java/kr/codesqaud/cafe/question/domain/Question.java
  src/main/java/kr/codesqaud/cafe/question/domain/QuestionEntity.java
  src/main/java/kr/codesqaud/cafe/question/repository/CollectionFrameWorkQuestionRepository.java
  src/main/java/kr/codesqaud/cafe/question/repository/H2QuestionRepository.java
  src/main/java/kr/codesqaud/cafe/question/repository/QuestionRepository.java
  src/main/java/kr/codesqaud/cafe/question/repository/TempQuestionTable.java
  src/main/java/kr/codesqaud/cafe/question/service/QuestionService.java
  src/main/java/kr/codesqaud/cafe/question_comment/controller/CommentController.java
  src/main/java/kr/codesqaud/cafe/question_comment/controller/request/CommentPagingInfoRequestDTO.java
  src/main/java/kr/codesqaud/cafe/question_comment/controller/request/CommentWriteRequestDTO.java
  src/main/java/kr/codesqaud/cafe/question_comment/controller/response/CommentResponseDTO.java
  src/main/java/kr/codesqaud/cafe/question_comment/domain/CommentEntity.java
  src/main/java/kr/codesqaud/cafe/question_comment/exception/CommentNotExistException.java
  src/main/java/kr/codesqaud/cafe/question_comment/repository/CommentRepository.java
  src/main/java/kr/codesqaud/cafe/question_comment/repository/H2CommentRepository.java
  src/main/java/kr/codesqaud/cafe/question_comment/service/CommentService.java
  src/main/java/kr/codesqaud/cafe/user/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/user/controller/request/SignUpRequestDTO.java
  src/main/java/kr/codesqaud/cafe/user/controller/response/AuthSession.java
  src/main/java/kr/codesqaud/cafe/user/controller/response/UserResponseDTO.java
  src/main/java/kr/codesqaud/cafe/user/domain/UserEntity.java
  src/main/java/kr/codesqaud/cafe/user/repository/CollectionFrameworkUserRepository.java
  src/main/java/kr/codesqaud/cafe/user/repository/H2UserRepository.java
  src/main/java/kr/codesqaud/cafe/user/repository/TempUserTable.java
  src/main/java/kr/codesqaud/cafe/user/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/user/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/schema.sql
  src/main/resources/static/js/qna.show.js
  src/test/java/kr/codesqaud/cafe/common/domain/PageHandlerTest.java
  src/test/java/kr/codesqaud/cafe/question/QuestionControllerTest.java
  src/test/java/kr/codesqaud/cafe/question/QuestionServiceTest.java
Labels: step-5, step-6, step-7, step-8

#208 [JAJA] step-3 구현(배포 제외)
  README.md
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/BasicArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/BasicUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcUserRepository.java
  src/main/java/kr/codesqaud/cafe/repository/UserRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/schema.sql
  src/main/resources/templates/index.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/updateForm.html
Labels: bug, enhancement, step-2, step-3

#218 [Albert] 테스트 코드 추가
  build.gradle
  src/main/java/kr/codesquad/cafe/CafeApplication.java
  src/main/java/kr/codesquad/cafe/comment/Comment.java
  src/main/java/kr/codesquad/cafe/comment/CommentNotFoundException.java
  src/main/java/kr/codesquad/cafe/comment/CommentService.java
  src/main/java/kr/codesquad/cafe/comment/UnauthorizedDeleteCommentException.java
  src/main/java/kr/codesquad/cafe/config/WebConfig.java
  src/main/java/kr/codesquad/cafe/global/AppStartupRunner.java
  src/main/java/kr/codesquad/cafe/global/PagesInfo.java
  src/main/java/kr/codesquad/cafe/global/auth/AuthBeforeAdvice.java
  src/main/java/kr/codesquad/cafe/post/Post.java
  src/main/java/kr/codesquad/cafe/post/PostIdToPostConverter.java
  src/main/java/kr/codesquad/cafe/post/PostService.java
  src/main/java/kr/codesquad/cafe/post/controller/MainController.java
  src/main/java/kr/codesquad/cafe/post/controller/PostCommentController.java
  src/main/java/kr/codesquad/cafe/post/controller/PostController.java
  src/main/java/kr/codesquad/cafe/post/controller/PostControllerExceptionHandler.java
  src/main/java/kr/codesquad/cafe/post/dto/PostForm.java
  src/main/java/kr/codesquad/cafe/post/dto/SimplePostForm.java
  src/main/java/kr/codesquad/cafe/user/JoinFormValidator.java
  src/main/java/kr/codesquad/cafe/user/UserService.java
  src/main/java/kr/codesquad/cafe/user/annotation/ValidTwoPassword.java
  src/main/java/kr/codesquad/cafe/user/controller/UserController.java
  src/main/java/kr/codesquad/cafe/user/controller/UserControllerExceptionHandler.java
  src/main/java/kr/codesquad/cafe/user/controller/UserProfileController.java
  src/main/java/kr/codesquad/cafe/user/domain/User.java
  src/main/java/kr/codesquad/cafe/user/dto/JoinForm.java
  src/main/java/kr/codesquad/cafe/user/dto/ProfileEditForm.java
  src/main/java/kr/codesquad/cafe/user/dto/ProfileForm.java
  src/main/java/kr/codesquad/cafe/user/dto/UserForm.java
  src/main/java/kr/codesquad/cafe/user/exception/ExistsEmailException.java
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/user/joinFailed.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/loginFailed.html
  src/test/java/kr/codesquad/cafe/comment/CommentServiceTest.java
  src/test/java/kr/codesquad/cafe/comment/CommentTest.java
  src/test/java/kr/codesquad/cafe/post/PostControllerTest.java
  src/test/java/kr/codesquad/cafe/post/PostServiceTest.java
  src/test/java/kr/codesquad/cafe/post/PostTest.java
  src/test/java/kr/codesquad/cafe/post/controller/MainControllerTest.java
  src/test/java/kr/codesquad/cafe/post/controller/PostCommentControllerTest.java
  src/test/java/kr/codesquad/cafe/post/controller/PostControllerTest.java
  src/test/java/kr/codesquad/cafe/post/dto/PostFormTest.java
  src/test/java/kr/codesquad/cafe/post/dto/SimplePostFormTest.java
  src/test/java/kr/codesquad/cafe/user/UserControllerTest.java
  src/test/java/kr/codesquad/cafe/user/UserRepositoryTest.java
  src/test/java/kr/codesquad/cafe/user/UserServiceTest.java
  src/test/java/kr/codesquad/cafe/user/controller/UserControllerTest.java
  src/test/java/kr/codesquad/cafe/user/controller/UserProfileControllerTest.java
  src/test/java/kr/codesquad/cafe/user/domain/UserTest.java
  src/test/java/kr/codesquad/cafe/user/dto/JoinFormTest.java
  src/test/java/kr/codesquad/cafe/user/dto/ProfileEditFormTest.java
  src/test/java/kr/codesquad/cafe/user/dto/ProfileFormTest.java
  src/test/java/kr/codesquad/cafe/user/dto/UserFormTest.java
  src/test/resources/application.properties
Labels: step-8

#225 [takealook] step6,7 댓글 기능
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/MainController.java
  src/main/java/kr/codesqaud/cafe/controller/ReplyController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/controller/dto/ArticleDto.java
  src/main/java/kr/codesqaud/cafe/controller/dto/ReplyDto.java
  src/main/java/kr/codesqaud/cafe/controller/dto/UserDto.java
  src/main/java/kr/codesqaud/cafe/controller/dto/request/articleRequest/ArticleWithReplyCount.java
  src/main/java/kr/codesqaud/cafe/controller/dto/request/articleRequest/PostEditRequest.java
  src/main/java/kr/codesqaud/cafe/controller/dto/request/articleRequest/PostRequest.java
  src/main/java/kr/codesqaud/cafe/controller/dto/request/replyRequest/ReplyEditRequest.java
  src/main/java/kr/codesqaud/cafe/controller/dto/request/replyRequest/ReplyRequest.java
  src/main/java/kr/codesqaud/cafe/controller/dto/request/userRequest/JoinRequest.java
  src/main/java/kr/codesqaud/cafe/controller/dto/request/userRequest/LoginRequest.java
  src/main/java/kr/codesqaud/cafe/controller/dto/request/userRequest/ProfileEditRequest.java
  src/main/java/kr/codesqaud/cafe/controller/modelBuilder/ModelBuilder.java
  src/main/java/kr/codesqaud/cafe/domain/Article.java
  src/main/java/kr/codesqaud/cafe/domain/Reply.java
  src/main/java/kr/codesqaud/cafe/domain/User.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/JdbcReplyRepository.java
  src/main/java/kr/codesqaud/cafe/repository/ReplyRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/ReplyService.java
  src/main/java/kr/codesqaud/cafe/service/UserService.java
  src/main/java/kr/codesqaud/cafe/service/util/Utility.java
  src/main/resources/application.properties
  src/main/resources/schema.sql
  src/main/resources/templates/fragments/login_navbar.html
  src/main/resources/templates/fragments/navbar.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login_index.html
  src/main/resources/templates/qna/edit_form.html
  src/main/resources/templates/qna/failed.html
  src/main/resources/templates/qna/form.html
  src/main/resources/templates/qna/reply.html
  src/main/resources/templates/qna/reply_edit_form.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/edit_form.html
  src/main/resources/templates/user/list.html
  step6&7-README.md
Labels: step-6, step-7

#236 [ light ] STEP - 8 게시글 페이징 , 댓글 더보기 구현
  src/main/java/kr/codesqaud/cafe/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/controller/UserController.java
  src/main/java/kr/codesqaud/cafe/domain/article/Article.java
  src/main/java/kr/codesqaud/cafe/domain/article/repository/ArticleJdbcRepository.java
  src/main/java/kr/codesqaud/cafe/domain/article/repository/ArticleMemoryRepository.java
  src/main/java/kr/codesqaud/cafe/domain/article/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/domain/reply/repository/ReplyMysqlRepository.java
  src/main/java/kr/codesqaud/cafe/domain/reply/repository/ReplyRepository.java
  src/main/java/kr/codesqaud/cafe/dto/ArticleResponseDto.java
  src/main/java/kr/codesqaud/cafe/dto/LoginDto.java
  src/main/java/kr/codesqaud/cafe/dto/Paging.java
  src/main/java/kr/codesqaud/cafe/dto/ReplyResponseDto.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/show.html
Labels: step-8

#235 [Jinny] 리팩토링 및 게시글 삭제 기능 구현
  README.md
  src/main/java/kr/codesqaud/cafe/GlobalExceptionHandler.java
  src/main/java/kr/codesqaud/cafe/article/Article.java
  src/main/java/kr/codesqaud/cafe/article/ArticleController.java
  src/main/java/kr/codesqaud/cafe/article/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/article/ArticleRepositoryImpl.java
  src/main/java/kr/codesqaud/cafe/article/ArticleService.java
  src/main/java/kr/codesqaud/cafe/article/dto/ArticleRequestDto.java
  src/main/java/kr/codesqaud/cafe/article/dto/ArticleResponseDto.java
  src/main/java/kr/codesqaud/cafe/exception/article/ArticleNotFoundException.java
  src/main/java/kr/codesqaud/cafe/exception/article/InvalidArticleDeletionException.java
  src/main/java/kr/codesqaud/cafe/exception/article/InvalidRequesterIdException.java
  src/main/java/kr/codesqaud/cafe/exception/user/UserNotFoundException.java
  src/main/java/kr/codesqaud/cafe/login/LoginRequestDto.java
  src/main/java/kr/codesqaud/cafe/reply/Reply.java
  src/main/java/kr/codesqaud/cafe/reply/ReplyController.java
  src/main/java/kr/codesqaud/cafe/reply/ReplyRepository.java
  src/main/java/kr/codesqaud/cafe/reply/ReplyRepositoryImpl.java
  src/main/java/kr/codesqaud/cafe/reply/ReplyService.java
  src/main/java/kr/codesqaud/cafe/user/User.java
  src/main/java/kr/codesqaud/cafe/user/UserController.java
  src/main/java/kr/codesqaud/cafe/user/UserRepository.java
  src/main/java/kr/codesqaud/cafe/user/UserRepositoryImpl.java
  src/main/java/kr/codesqaud/cafe/user/UserService.java
  src/main/java/kr/codesqaud/cafe/user/dto/LoginRequestDto.java
  src/main/java/kr/codesqaud/cafe/user/dto/ProfileResponseDto.java
  src/main/java/kr/codesqaud/cafe/user/dto/SignUpRequestDto.java
  src/main/resources/scheme.sql
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/show.html
  src/main/resources/templates/user/form.html
  src/main/resources/templates/user/list.html
  src/main/resources/templates/user/login.html
  src/test/java/kr/codesqaud/cafe/article/ArticleRepositoryImplTest.java
  src/test/java/kr/codesqaud/cafe/article/ArticleServiceTest.java
  src/test/java/kr/codesqaud/cafe/repository/UserRepositoryImplTest.java
  src/test/resources/scheme.sql
Labels: enhancement

#217 [무비] Step 8 게시글 페이징 구현
  src/main/java/kr/codesqaud/cafe/article/controller/ArticleController.java
  src/main/java/kr/codesqaud/cafe/article/dto/ResponsePaginationDto.java
  src/main/java/kr/codesqaud/cafe/article/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/article/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/comment/controller/CommentController.java
  src/main/java/kr/codesqaud/cafe/comment/domain/Comment.java
  src/main/java/kr/codesqaud/cafe/comment/service/CommentService.java
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/user/dto/ResponseUserPreview.java
  src/main/java/kr/codesqaud/cafe/user/repository/UserRepository.java
  src/main/resources/application.properties
  src/main/resources/schema.sql
  src/main/resources/templates/articles/list.mustache
  src/main/resources/templates/articles/write-form.mustache
  src/main/resources/templates/layout/header.mustache
Labels: step-8

#223 [브루니] ajax 댓글 삭제 / 로깅 / 페이징 구현
  .gitignore
  src/main/java/kr/codesqaud/cafe/common/argumentresolver/PageableArgumentResolver.java
  src/main/java/kr/codesqaud/cafe/common/filter/RequestContext.java
  src/main/java/kr/codesqaud/cafe/common/filter/RequestServletWrappingFilter.java
  src/main/java/kr/codesqaud/cafe/config/MvcConfig.java
  src/main/java/kr/codesqaud/cafe/controller/CommentController.java
  src/main/java/kr/codesqaud/cafe/controller/MainController.java
  src/main/java/kr/codesqaud/cafe/exception/GlobalExceptionHandler.java
  src/main/java/kr/codesqaud/cafe/exception/LogMessageGenerator.java
  src/main/java/kr/codesqaud/cafe/repository/ArticleRepository.java
  src/main/java/kr/codesqaud/cafe/repository/impl/ArticleJdbcRepository.java
  src/main/java/kr/codesqaud/cafe/service/ArticleService.java
  src/main/java/kr/codesqaud/cafe/service/paging/Page.java
  src/main/java/kr/codesqaud/cafe/service/paging/PageNumber.java
  src/main/java/kr/codesqaud/cafe/service/paging/Pageable.java
  src/main/java/kr/codesqaud/cafe/service/paging/PaginationService.java
  src/main/resources/logback-spring.xml
  src/main/resources/logback/console/console-appender.xml
  src/main/resources/logback/file/file-error-appender.xml
  src/main/resources/logback/file/file-info-appender.xml
  src/main/resources/logback/file/file-warn-appender.xml
  src/main/resources/logback/properties/logback-properties.xml
  src/main/resources/static/js/comment.js
  src/main/resources/templates/index.html
  src/main/resources/templates/qna/show.html
  src/test/java/kr/codesqaud/cafe/controller/ArticleControllerTest.java
  src/test/java/kr/codesqaud/cafe/controller/CommentControllerTest.java
  src/test/java/kr/codesqaud/cafe/controller/UserControllerTest.java
  src/test/java/kr/codesqaud/cafe/service/ArticleServiceTest.java
Labels: step-8
